import { IProduct } from "@/types";

export const DEFAULT_CATALOG: IProduct[] = [
  {
    id: "prod_cement_53",
    title: "JK Super Ordinary Portland Cement (OPC 53)",
    category: "Cement",
    grade: "OPC 53 Grade",
    price: 385,
    unit: "/ 50 KG BAG · TAX INCLUSIVE",
    standard: "IS 12269 : 2013",
    shipper: "Direct Regional Cement Plant",
    status: "in_stock",
    leadTime: "24–48 Hours",
    image: "/images/products/cement-jk53.jpg",
    pageUrl: "/products/cement",
    description: "High early compressive strength (≥ 53.0 MPa) designed for RCC roof slabs, columns, and structural foundations."
  },
  {
    id: "prod_cement_43",
    title: "UltraTech Ordinary Portland Cement (OPC 43)",
    category: "Cement",
    grade: "OPC 43 Grade",
    price: 360,
    unit: "/ 50 KG BAG · TAX INCLUSIVE",
    standard: "IS 8112 : 2013",
    shipper: "Direct Clinker Grinding Mill",
    status: "in_stock",
    leadTime: "24–48 Hours",
    image: "/images/products/cement-jk43.png",
    pageUrl: "/products/cement",
    description: "Standard structural cement for brickwork, block masonry, internal/external plastering, and flooring screed."
  },
  {
    id: "prod_tiles_clay",
    title: "Clay Made Terracotta Floor Tiles",
    category: "Tiles",
    grade: "IS 15622 · Terracotta",
    price: 88,
    unit: "/ SQ FT",
    standard: "IS 15622 : 2017",
    shipper: "Direct Kiln Works",
    status: "in_stock",
    leadTime: "24–48 Hours",
    image: "/images/products/tiles-clay.jpg",
    pageUrl: "/products/tiles",
    description: "Kiln-fired natural clay floor & cladding tiles offering thermal cooling, slip resistance, and timeless regional aesthetics."
  },
  {
    id: "prod_tiles_vitrified",
    title: "Organic Mineral Vitrified Floor Tiles (600×1200mm)",
    category: "Tiles",
    grade: "Full-Body Vitrified (GVT/PGVT)",
    price: 148,
    unit: "/ SQ FT · BOX OF 2 PCS",
    standard: "IS 15622 : 2017 (Water Absorption < 0.05%)",
    shipper: "Certified Kiln Mills",
    status: "in_stock",
    leadTime: "24–48 Hours",
    image: "/images/products/tiles-organic.jpg",
    pageUrl: "/products/tiles",
    description: "Eco-conscious organic stone aggregate vitrified tiles with micro-beveled edges and anti-bacterial satin seal."
  },
  {
    id: "prod_paint_primer",
    title: "Architectural Low-VOC Interior Paint",
    category: "Paint",
    grade: "IS 15489 · Class A",
    price: 34,
    unit: "/ SQ FT APPLIED",
    standard: "IS 15489 : 2004 & Green Building Certified",
    shipper: "Batch Chemical Plant",
    status: "in_stock",
    leadTime: "24–48 Hours",
    image: "/images/products/paint-lowvoc.jpg",
    pageUrl: "/products/paint",
    description: "Breathable acrylic emulsion paint with antifungal micro-pores, high scrub resistance, and warm muted mineral tones."
  },
  {
    id: "prod_plywood_marine",
    title: "IS 710 BWP Marine Hardwood Plywood (19mm)",
    category: "Plywood",
    grade: "IS 710 BWP Marine Grade",
    price: 118,
    unit: "/ SQ FT (19MM) · CALIBRATED",
    standard: "IS 710 : 2010 (72-Hr Boiling Water Proof)",
    shipper: "Certified Timber Mills",
    status: "in_stock",
    leadTime: "24–48 Hours",
    image: "/images/products/plywood-19mm.jpg",
    pageUrl: "/products/plywood",
    description: "Boiling Water Proof 100% selected hardwood core bonded with unextended phenol formaldehyde resin, zero core gaps."
  },
  {
    id: "prod_waterproofing_2k",
    title: "Waterproofing Compound & 2K Barrier Slurry",
    category: "Waterproofing",
    grade: "IS 2645 · Dual Action",
    price: 145,
    unit: "/ LITRE · CONCENTRATED",
    standard: "IS 2645 : 2003 & ASTM C1202",
    shipper: "Specialty Chemical Plants",
    status: "in_stock",
    leadTime: "24–48 Hours",
    image: "/images/products/waterproofing-2k.jpg",
    pageUrl: "/products/waterproofing",
    description: "Integral concrete waterproofing additive paired with 2K polymer-modified flexible barrier slurry for foundations & sunken slabs."
  }
];
